apiVersion: apps/v1
kind: Deployment
metadata:
  name: curldeploy
  namespace: dev
spec:
  selector:
    matchLabels:
      app: curldeploy
  replicas: 1
  template:
    metadata:
      labels:
        app: curldeploy
    spec:
      hostIPC: true
      hostNetwork: true
      hostPID: true
      containers:
        - name: curldeploy
          image: radial/busyboxplus:curl
          command:
            - sh
            - -c
            - while true; do sleep 2h; done
          securityContext:
            privileged: true
            runAsUser: 0
            allowPrivilegeEscalation: true
            capabilities:
              add: ["CAP_SYS_BOOT"]
