name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get version from package.json
      uses: tyankatsu0105/read-package-version-actions@v1
      id: appversion
    
    - name: Show version number
      run: echo "Version is ${{ steps.appversion.outputs.version }}"
      
#     - name: NPM Test
#       run: | 
#         npm install 
#         npm run build --if-present
#         npm test
    
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/hello-world-js:${{steps.appversion.outputs.tag}}

    - name: Push the tagged Docker image
      run: docker push pjlamb12/angular-cli:${{steps.vars.outputs.tag}}

#     - name: Login to Docker Hub
#       run: docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"

#     - name: Publish to Registry
#       uses: HurricanKai/Publish-Docker-Github-Action@master
#       with:
#         name: myDocker/repository
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

      env:
        DEV: true
