name: CI-CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # job1
  build_test:
    name: Build & Test App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install
          npm ci

      # build and test the apps
      - name: build & test
        run: |
          npm run build
          npm run test
  # job
  push_to_docker_hub:
    name: Push Images to DockerHub
    runs-on: ubuntu-latest
    needs: [build_test]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Get version from package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: appversion

      - name: package.json version number
        run: echo "Version is ${{ steps.appversion.outputs.version }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-world-js:${{ steps.appversion.outputs.version }}

      - name: New Docker Image version
        run: ${{ secrets.DOCKER_USERNAME }}/hello-world-js:${{ steps.appversion.outputs.version }}

      # - name: Login to DockerHub Registry
      #   run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/hello-world-js:${{steps.appversion.outputs.version}}

      # - name: Push the tagged Docker image
      #   run: docker push ${{secrets.DOCKER_USERNAME}}/hello-world-js:${{steps.appversion.outputs.version}}

  # # job
  # minikube_deploy:
  #   name: Push Images to DockerHub
  #   runs-on: ubuntu-latest
  #   needs: [push_to_docker_hub]

  #   steps:
  #     - name: Setup Minikube
  #       uses: manusa/actions-setup-minikube@v2.4.3
  #       with:
  #         minikube version: "v1.25.1"
  #         kubernetes version: "v1.23.4"
  #         # github token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Sleep for 20 seconds
  #       uses: jakejarvis/wait-action@master
  #       with:
  #         time: "20s"
  #     - name: Interact with the cluster
  #       run: |
  #         kubectl get nodes
  #         kubectl get po -A
  #     - name: Update the deploy1.yaml with new Image
  #       run: |
  #         sed -e "s/tag/${{steps.appversion.outputs.version}}/g" ./k8s-resources/deploy1.yaml > ./k8s-resources/deploy1-upd.yaml
  #     - name: Deployment to minikube cluster
  #       run: kubectl apply -f ./k8s-resources/deploy1-upd.yaml

  #     - name: Sleep for 10 seconds
  #       uses: jakejarvis/wait-action@master
  #       with:
  #         time: "10s"

  #     - name: Check hello-world-svc
  #       run: |
  #         kubectl get svc -o wide
  #         kubectl get ep -o wide

  #     # - name: test hello-world
  #     #   run: |
  #     #     curl $(kubectl get svc hello-world-svc -o jsonpath='{.spec.clusterIP}'): $(kubectl get svc hello-world-svc -o jsonpath='{.spec.ports[0].port}')
