name: CI-CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  # job1
  build_test:
    name: Build & Test App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Run build and test only if the commit message says build
    if: "contains(github.event.commits[0].message, 'build')"

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install
          npm ci

      # build and test the apps
      - name: Build & test
        run: |
          npm run build
          npm run test

  # job
  build_push_image:
    name: Build & Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    needs: [build_test]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set package info variables
        id: projectinfo
        uses: codex-team/action-nodejs-package-info@v1
        env:
          AUTHOR: ${{ steps.projectinfo.outputs.author }}
        with:
          name: ${{ steps.projectinfo.outputs.name }}
          version: ${{ steps.projectinfo.outputs.version }}

      - name: Get the output
        run: |
          echo "name: ${{ steps.projectinfo.outputs.name }}"
          echo "version: ${{ steps.projectinfo.outputs.version }}"

      - name: Package.json version number
        run: echo "Version is ${{ steps.projectinfo.outputs.version }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ steps.projectinfo.outputs.name }}:${{ steps.projectinfo.outputs.version }}

      - name: New Docker Image version
        run: echo ${{ secrets.DOCKER_USERNAME }}/${{ steps.projectinfo.outputs.name }}:${{ steps.projectinfo.outputs.version }}

    outputs:
      name: ${{ steps.projectinfo.outputs.name }}
      version: ${{ steps.projectinfo.outputs.version }}

  # scan job
  voln_scan_image:
    name: Scan Image for vulnerabilities
    runs-on: ubuntu-latest
    needs: [build_push_image]

    steps:
      - name: Docker Image to Scan
        run: echo ${{ secrets.DOCKER_USERNAME }}/${{ needs.build_push_image.outputs.name }}:${{ needs.build_push_image.outputs.version }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ needs.build_push_image.outputs.name }}:${{ needs.build_push_image.outputs.version }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"

  #job
  update_kube_yaml:
    name: Update Deployment YAML file with images
    runs-on: ubuntu-latest
    needs: [voln_scan_image]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup git config
        run: |
          mkdir -p ./clusters/k8s-cluster/default

      - name: Update the deploy1.yaml with new Image
        run: |
          sed -e "s/tag/${{ needs.build_push_image.outputs.version }}/g" ./k8s-resources/deploy1.tmpl > ./clusters/k8s-cluster/default/deploy1.yaml

      - name: Verify deploy1.yaml image
        run: cat ./clusters/k8s-cluster/default/deploy1.yaml | grep -i image

  # job
  trigger_flux:
    name: Push Yaml and trigger Flux
    runs-on: ubuntu-latest
    needs: [update_kube_yaml]

    steps:
      # - name: commit
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     # Optional. Commit message for the created commit.
      #     # Defaults to "Apply automatic changes"
      #     commit_message: Automated Change
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: Commit YAML - Trigger flux CD
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "build updated yaml"
          git push github HEAD:${GITHUB_REF}

  # # job
  # deploy_to_google_cloud:
  #   name: Deploy to GCP
  #   runs-on: ubuntu-latest
  #   needs: [update_kube_yaml]

  #   #https://github.com/YannMjl/nodejs-demo-app/blob/main/.github/workflows/main.yml

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Setup gcloud CLI
  #       uses: google-github-actions/setup-gcloud@master

  #     - name: Deploy GKE
  #       run: echo "Deploy GKE"
